# Generated by Django 4.2.3 on 2023-07-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='customer',
        ),
    ]
