# Generated by Django 4.2.3 on 2023-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_portfolio_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
    ]
