# Generated by Django 4.2.3 on 2023-08-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_company_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date_purchased',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='price_purchased',
            field=models.DecimalField(decimal_places=2, default=20.5, max_digits=6),
            preserve_default=False,
        ),
    ]
